### ISSUE TITLE
For questionnaire breast-cancer-study-survey use wizard widget 

### ISSUE THREAD

**Issue by ir4y** [HadleyLab/ucfwealth#12]
https://github.com/HadleyLab/ucfwealth/blob/emr/resources/seeds/Questionnaire/breast-cancer-study-survey.yaml

**Comment by yanabeda** [comment]
@vesnushka the issue with this version of the widget, that the complete button at the bottom saves the whole questionnaire. We need a way to navigate over tabs. here is how Alex solved it

![Image](https://github.com/user-attachments/assets/859526ef-3e6f-4344-9baf-090cf7b8c535)
