### ISSUE TITLE
Please, check the error in the files list

### ISSUE THREAD

**Issue by yanabeda** [HadleyLab/ucfwealth#3]
<img width="539" alt="Screenshot 2024-01-24 at 6 23 40 pm" src="https://github.com/HadleyLab/ucfwealth/assets/3823356/cb2e8f7f-1787-45b7-9a28-5aa55bb5e820">

**Comment by ir4y** [comment]
If the system can't generate image preview for the file, it should say 'image preview is not available' instead of   'Unknown error'
